namespace OSHManagement.Models.ViewModels
{
    /// <summary>
    /// Configuration for DetailCard component
    /// Full-width card showing entity details with icon, title, fields, and actions
    /// </summary>
    public class DetailCardConfig
    {
        public string CardId { get; set; } = "detailCard";
        public string Icon { get; set; } = "ri-folder-line";
        public string IconColor { get; set; } = "primary"; // primary, secondary, success, danger, warning, info
        public string BorderColor { get; set; } = "primary"; // Left border and background color
        public string Title { get; set; } = "";
        public string? Subtitle { get; set; }
        public string? Category { get; set; } // e.g., "Category Type", "Department"

        // Fields displayed in the card body
        public List<DetailField> Fields { get; set; } = new List<DetailField>();

        // Action buttons on the right
        public List<DetailCardAction> Actions { get; set; } = new List<DetailCardAction>();

        // Optional badge/status
        public DetailBadge? StatusBadge { get; set; }

        // Layout options
        public bool ShowCard { get; set; } = true; // If false, renders without card wrapper
    }

    /// <summary>
    /// Individual field in detail card
    /// </summary>
    public class DetailField
    {
        public string Label { get; set; } = "";
        public string Value { get; set; } = "";
        public string? Icon { get; set; } // Optional icon before label
        public bool IsHtml { get; set; } = false; // If true, renders Value as raw HTML
        public string? Href { get; set; } // Makes value a link if provided
        public DetailBadge? Badge { get; set; } // Optional badge instead of plain text
    }

    /// <summary>
    /// Badge configuration for status indicators
    /// </summary>
    public class DetailBadge
    {
        public string Text { get; set; } = "";
        public string Color { get; set; } = "primary"; // primary, secondary, success, danger, warning, info, light, dark
        public string? Icon { get; set; }
    }

    /// <summary>
    /// Action button configuration
    /// </summary>
    public class DetailCardAction
    {
        public string Text { get; set; } = "";
        public string? Icon { get; set; }
        public string? Url { get; set; }
        public string ButtonStyle { get; set; } = "primary"; // primary, secondary, success, danger, warning, info, light, outline-primary, etc.
        public string ButtonSize { get; set; } = "sm"; // sm, md, lg
        public bool IsDropdown { get; set; } = false;
        public List<DropdownItem>? DropdownItems { get; set; }
        public string? OnClick { get; set; } // JavaScript function name
    }

    /// <summary>
    /// Dropdown menu item
    /// </summary>
    public class DropdownItem
    {
        public string Text { get; set; } = "";
        public string? Icon { get; set; }
        public string? Url { get; set; }
        public string? OnClick { get; set; }
        public bool IsDivider { get; set; } = false;
    }

    /// <summary>
    /// Presentation ViewModel (generated by extension method)
    /// </summary>
    public class DetailCardViewModel
    {
        public string CardId { get; set; } = "";
        public string Icon { get; set; } = "";
        public string IconColor { get; set; } = "primary";
        public string BorderColor { get; set; } = "primary";
        public string Title { get; set; } = "";
        public string? Subtitle { get; set; }
        public string? Category { get; set; }
        public List<DetailField> Fields { get; set; } = new List<DetailField>();
        public List<DetailCardAction> Actions { get; set; } = new List<DetailCardAction>();
        public DetailBadge? StatusBadge { get; set; }
        public bool ShowCard { get; set; } = true;

        // Computed properties
        public bool HasActions => Actions.Any();
        public bool HasFields => Fields.Any();
        public string IconColorClass => $"bg-{IconColor}-transparent text-{IconColor}";
    }
}
